---
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
manual_evaluation: false
choices:
- value: Pepita, Norita y Pepo son polim贸rficas para Emilce.
  checked: true
- value: Pepita, Norita y Pepo son polim贸rficas para Pachorra.
  checked: false
- value: Pepita, Norita y Pepo no son polim贸rficas para Pachorra.
  checked: true
- value: Pepita y Pepo son polim贸rficas para Pachorra.
  checked: true
